/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type CallToAction = {
  _type: 'callToAction'
  heading: string
  text?: string
  buttonText?: string
  link?: Link
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  post?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'post'
  }
  openInNewTab?: boolean
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
      post?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'post'
      }
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    linkType?: 'href' | 'page' | 'post'
    href?: string
    page?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'page'
    }
    post?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'post'
    }
    openInNewTab?: boolean
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
      post?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'post'
      }
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'person'
  }
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
  }
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | CallToAction
  | Link
  | InfoSection
  | BlockContent
  | Settings
  | Page
  | Post
  | Person
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./sanity/lib/queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "project"] | order(submittedAt desc) {    _id,    projectName,    "slug": slug.current,    tagline,    description,    githubUrl,    demoUrl,    "thumbnail": screenshots[0],    submittedAt,    status,    analysisData {      aiSummaryForJudges,      latestAnalysisAt,      tags    },    sponsorIntegrations[] {      sponsorSlug,      sponsorName,      integrationDepth,      technicalScore,      creativityScore,      toolsUsed    },    team[]-> {      _id,      name,      githubUsername,      avatar    }  }
export type AllProjectsQueryResult = Array<never>
// Variable: projectQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    projectName,    tagline,    description,    githubUrl,    demoUrl,    videoUrl,    screenshots,    githubData,    submittedAt,    status,    analysisData {      aiSummaryForJudges,      latestAnalysisAt,      tags    },    sponsorIntegrations[] {      sponsorSlug,      sponsorName,      aiSummary,      integrationDepth,      technicalScore,      creativityScore,      toolsUsed,      codeEvidence,      userFacingFeatures    },    team[]-> {      _id,      name,      email,      githubUsername,      avatar,      bio    },    "judgeNotes": *[_type == "judgeNote" && project._ref == ^._id && isPublic == true] | order(createdAt desc) {      _id,      judgeName,      judgeRole,      sponsorAffiliation,      comment,      scoreOverride,      highlightedFor,      createdAt    }  }
export type ProjectQueryResult = null
// Variable: projectsBySponsorQuery
// Query: *[_type == "project" && $sponsorSlug in sponsorIntegrations[].sponsorSlug] | order(sponsorIntegrations[sponsorSlug == $sponsorSlug][0].technicalScore desc) {    _id,    projectName,    "slug": slug.current,    tagline,    "thumbnail": screenshots[0],    "sponsorIntegration": sponsorIntegrations[sponsorSlug == $sponsorSlug][0] {      aiSummary,      integrationDepth,      technicalScore,      creativityScore,      toolsUsed    },    team[]-> {      _id,      name,      avatar    }  }
export type ProjectsBySponsorQueryResult = Array<never>
// Variable: allJudgeNotesForProjectQuery
// Query: *[_type == "judgeNote" && project._ref == $projectId] | order(createdAt desc) {    _id,    judgeName,    judgeRole,    sponsorAffiliation,    comment,    scoreOverride,    isPublic,    highlightedFor,    createdAt  }
export type AllJudgeNotesForProjectQueryResult = Array<never>
// Variable: projectSlugsQuery
// Query: *[_type == "project" && defined(slug.current)]  {"slug": slug.current}
export type ProjectSlugsQueryResult = Array<never>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "project"] | order(submittedAt desc) {\n    _id,\n    projectName,\n    "slug": slug.current,\n    tagline,\n    description,\n    githubUrl,\n    demoUrl,\n    "thumbnail": screenshots[0],\n    submittedAt,\n    status,\n    analysisData {\n      aiSummaryForJudges,\n      latestAnalysisAt,\n      tags\n    },\n    sponsorIntegrations[] {\n      sponsorSlug,\n      sponsorName,\n      integrationDepth,\n      technicalScore,\n      creativityScore,\n      toolsUsed\n    },\n    team[]-> {\n      _id,\n      name,\n      githubUsername,\n      avatar\n    }\n  }\n': AllProjectsQueryResult
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    projectName,\n    tagline,\n    description,\n    githubUrl,\n    demoUrl,\n    videoUrl,\n    screenshots,\n    githubData,\n    submittedAt,\n    status,\n    analysisData {\n      aiSummaryForJudges,\n      latestAnalysisAt,\n      tags\n    },\n    sponsorIntegrations[] {\n      sponsorSlug,\n      sponsorName,\n      aiSummary,\n      integrationDepth,\n      technicalScore,\n      creativityScore,\n      toolsUsed,\n      codeEvidence,\n      userFacingFeatures\n    },\n    team[]-> {\n      _id,\n      name,\n      email,\n      githubUsername,\n      avatar,\n      bio\n    },\n    "judgeNotes": *[_type == "judgeNote" && project._ref == ^._id && isPublic == true] | order(createdAt desc) {\n      _id,\n      judgeName,\n      judgeRole,\n      sponsorAffiliation,\n      comment,\n      scoreOverride,\n      highlightedFor,\n      createdAt\n    }\n  }\n': ProjectQueryResult
    '\n  *[_type == "project" && $sponsorSlug in sponsorIntegrations[].sponsorSlug] | order(sponsorIntegrations[sponsorSlug == $sponsorSlug][0].technicalScore desc) {\n    _id,\n    projectName,\n    "slug": slug.current,\n    tagline,\n    "thumbnail": screenshots[0],\n    "sponsorIntegration": sponsorIntegrations[sponsorSlug == $sponsorSlug][0] {\n      aiSummary,\n      integrationDepth,\n      technicalScore,\n      creativityScore,\n      toolsUsed\n    },\n    team[]-> {\n      _id,\n      name,\n      avatar\n    }\n  }\n': ProjectsBySponsorQueryResult
    '\n  *[_type == "judgeNote" && project._ref == $projectId] | order(createdAt desc) {\n    _id,\n    judgeName,\n    judgeRole,\n    sponsorAffiliation,\n    comment,\n    scoreOverride,\n    isPublic,\n    highlightedFor,\n    createdAt\n  }\n': AllJudgeNotesForProjectQueryResult
    '\n  *[_type == "project" && defined(slug.current)]\n  {"slug": slug.current}\n': ProjectSlugsQueryResult
  }
}
